package com.flingoapp.flingo.ui.component

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.pager.PagerState
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.derivedStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.blur
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalInspectionMode
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.flingoapp.flingo.R
import com.flingoapp.flingo.data.model.MockData
import com.flingoapp.flingo.data.model.book.Book
import com.flingoapp.flingo.data.network.GenAiModel
import com.flingoapp.flingo.ui.CustomPreview
import com.flingoapp.flingo.ui.component.button.CustomElevatedButton
import com.flingoapp.flingo.ui.innerShadow
import com.flingoapp.flingo.ui.theme.FlingoColors
import com.flingoapp.flingo.ui.theme.FlingoTheme
import kotlinx.coroutines.launch


/**
 * Book item used to display the different book on the [com.flingoapp.flingo.ui.screen.HomeScreen]
 *
 * @param modifier
 * @param itemSize
 * @param pagerState
 * @param bookIndex
 * @param book
 * @param onClick
 */
@Composable
fun BookItem(
    modifier: Modifier = Modifier,
    itemSize: Dp,
    pagerState: PagerState,
    bookIndex: Int,
    book: Book,
    onClick: () -> Unit
) {
    val coroutineScope = rememberCoroutineScope()
    val context = LocalContext.current

    val noChaptersProvided by remember { derivedStateOf { (book.chapters.isEmpty()) } }

    //check if book is generated by AI
    val isGenerated by remember {
        mutableStateOf(GenAiModel.entries.any {
            book.author.equals(
                it.provider,
                ignoreCase = true
            )
        })
    }

    CustomElevatedButton(
        modifier = modifier.size(itemSize),
        shape = RoundedCornerShape(50.dp),
        backgroundColor = if (isGenerated) FlingoColors.Primary else FlingoColors.LightGray,
        elevation = 20.dp,
        animateButtonClick = bookIndex == pagerState.currentPage,
        isPressed = bookIndex != pagerState.currentPage || noChaptersProvided,
        onClick = {
            if (bookIndex != pagerState.currentPage) {
                coroutineScope.launch {
                    pagerState.animateScrollToPage(bookIndex)
                }
            } else {
                onClick()
            }
        },
        buttonContent = {
            Box(contentAlignment = Alignment.Center) {
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(top = 24.dp, start = 8.dp, end = 8.dp)
                        .blur(if (noChaptersProvided) 10.dp else 0.dp),
                    verticalArrangement = Arrangement.SpaceAround,
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    if (!LocalInspectionMode.current) {
                        //returns 0 if it does not exist
                        val coverImageResourceId: Int = context.resources.getIdentifier(
                            if (book.coverImage.isNullOrEmpty()) "flingo_red" else book.coverImage,
                            "drawable",
                            context.packageName
                        ).takeIf { it != 0 } ?: R.drawable.flingo_red

                        Image(
                            modifier = Modifier.weight(1f),
                            painter = painterResource(id = coverImageResourceId),
                            contentDescription = "Book Image Cover"
                        )
                    } else {
                        Image(
                            modifier = Modifier.weight(1f),
                            painter = painterResource(id = R.drawable.flingo_red),
                            contentDescription = "Book Image Cover"
                        )
                    }

                    Text(
                        modifier = Modifier
                            .padding(top = 24.dp)
                            .padding(bottom = 12.dp),
                        text = book.title,
                        style = MaterialTheme.typography.headlineLarge.copy(
                            fontSize = 48.sp,
                        ),
                        textAlign = TextAlign.Center
                    )

                    val maxAmountChapters =
                        if (noChaptersProvided) "-" else book.chapters.size.toString()
                    val chaptersCompleted =
                        if (noChaptersProvided) "-" else book.chapters.count { it.isCompleted }
                            .toString()

                    Column(
                        modifier = Modifier.padding(bottom = 16.dp),
                        verticalArrangement = Arrangement.Center,
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        Text(
                            text = "$chaptersCompleted/$maxAmountChapters abgeschlossen",
                            style = MaterialTheme.typography.bodyMedium.copy(
                                fontSize = 28.sp,
                                fontWeight = FontWeight.Medium
                            ),
                            textAlign = TextAlign.Center
                        )

                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(top = 12.dp)
                                .height(35.dp)
                        ) {
                            Box(
                                modifier = Modifier
                                    .fillMaxSize()
                                    .clip(RoundedCornerShape(50.dp))
                                    .background(Color.White)
                                    .innerShadow(
                                        shape = RoundedCornerShape(50.dp),
                                        color = Color.Black.copy(alpha = 0.5f),
                                        offsetY = 2.dp,
                                        offsetX = 2.dp,
                                        blur = 1.dp,
                                        spread = 2.dp
                                    ),
                                contentAlignment = Alignment.CenterStart,
                            ) {

                            }

                            val completedPercentage = if (!noChaptersProvided) {
                                chaptersCompleted.toFloat() / maxAmountChapters.toFloat()
                            } else {
                                0f
                            }

                            Box(
                                modifier = Modifier
                                    .fillMaxHeight()
                                    .fillMaxWidth(completedPercentage)
                                    .clip(RoundedCornerShape(50.dp))
                                    .background(FlingoColors.Success),
                                contentAlignment = Alignment.TopCenter
                            ) {
                                // progress bar shine effect
//                                Box(
//                                    modifier = Modifier
//                                        .fillMaxHeight(0.15f)
//                                        .fillMaxWidth(0.8f)
//                                        .offset(y = 8.dp)
//                                        .clip(RoundedCornerShape(50.dp))
//                                        .background(Color.White.copy(alpha = 0.7f))
//                                )
                            }
                        }
                    }
                }

                Text(
                    modifier = Modifier
                        .align(Alignment.TopStart)
                        .padding(vertical = 24.dp)
                        .background(
                            color = Color.White, shape = RoundedCornerShape(30)
                        )
                        .padding(16.dp),
                    text = book.author
                )

                if (noChaptersProvided) {
                    Icon(
                        modifier = Modifier.size((itemSize.value / 1.75).dp),
                        tint = Color.Black,
                        imageVector = Icons.Default.Lock,
                        contentDescription = "Chapter Locked"
                    )
                }
            }
        }
    )
}

@CustomPreview
@Composable
private fun BookItemPreview() {
    FlingoTheme {
        BookItem(
            itemSize = 500.dp,
            pagerState = rememberPagerState(pageCount = { 3 }),
            bookIndex = 0,
            book = MockData.book,
            onClick = {}
        )
    }
}